inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

RSpec/NotToNot:
  Enabled: false

Style/BlockDelimiters: # ブロックについて 2行以上ならdo end 1行なら{} 目的：spec/system/users_signup_specのエラーを除くため
  Enabled: false

Rails/HelperInstanceVariable: # helperメソッド内でインスタンス変数を使わない
  Enabled: false

RSpec/RepeatedExample: #　sitelayoutsスペックの保留部分のため
  Enabled: false

Style/AndOr: # app/controllers/users_controller.rb:16 and→&&
  Enabled: false

Layout/FirstHashElementLineBreak: # ハッシュの形式
  Enabled: false

Layout/MultilineHashBraceLayout: # ハッシュの形式
  Enabled: false

Style/ParenthesesAroundCondition: # unles文 ()で囲まない
  Enabled: false
