inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 135

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

RSpec/NotToNot:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/AndOr:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Airbnb/DefaultScope:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false
