inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/MixinUsage: #includeの位置 目的：spec/helpers/application_helperのエラーを除くため
  Enabled: false

RSpec/NotToNot:
  Enabled: false

Style/BlockDelimiters: # ブロックについて 2行以上ならdo end 1行なら{} 目的：spec/system/users_signup_specのエラーを除くため
  Enabled: false

Rails/HelperInstanceVariable: # helperメソッド内でインスタンス変数を使わない
  Enabled: false
