name: Tests and Deproy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.7
      - name: Build
        run: docker-compose build
      - name: DB setting
        run: |
          docker-compose run web rails db:create
          docker-compose run web rails db:migrate
      - name: Run RSpec
        run: docker-compose run web bundle exec rspec
      - name: Run Rubocop
        run: docker-compose run web bundle exec rubocop
  heroku-deproy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dry-dawn-42498"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
