name: Tests and Deproy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
    container:
      image: ishigamimasato/animalcafe
      credentials:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
      env:
        RAILS_ENV: test
    steps:
      - name: Setup Database
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Run RSpec
        run: bundle exec rspec
      - name: Run Rubocop
        run: bundle exec rubocop
  heroku-deproy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dry-dawn-42498"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
