name: Tests and Deproy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose exec web yarn install --check-files
          docker-compose exec web yarn upgrade
      - name: DB create
        run: docker-compose exec web rails db:create
      - name: Table create  
        run: docker-compose exec web rails db:migrate
      - name: Run RSpec
        run: docker-compose exec web bundle exec rspec
      - name: Run Rubocop
        run: docker-compose exec web bundle exec rubocop
  heroku-deproy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dry-dawn-42498"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
