name: Tests and Deproy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: DB and Table create
        run: |
          docker-compose run web rails db:create
          docker-compose run web rails db:migrate
      - name: Run container
        run: docker-compose up -d
      - name: Run RSpec
        run: docker-compose exec -T web bundle exec rspec
      - name: Run RuboCop    
        run: docker-compose exec -T web bundle exec rubocop
  heroku-deproy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "dry-dawn-42498"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
